
// --------------------------------------------------------------
// GENERATED FILE ----> DO NOT EDIT <---- CHANGES WILL BE LOST !!
// --------------------------------------------------------------

using CodeSmile.Luny;
using System;

namespace Lua.UnityEngine.CoreModule
{
    [Serializable]
    public sealed class UnityEngine_LuaModule_Loader : LunyLuaModuleLoader
    {
        public override void Load(LuaTable env)
        {
            base.Load(env);
            var SystemTable = GetOrCreateNamespaceTable(env, new[] { "System" });
            var UnityEngineTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine" });
            var UnityEngineAnalyticsTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Analytics" });
            var UnityEngineDiagnosticsTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Diagnostics" });
            var UnityEngineEventsTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Events" });
            var UnityEngineProfilingTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Profiling" });
            var UnityEngineSceneManagementTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "SceneManagement" });
            var UnityEngineScriptingTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Scripting" });
            var UnityEngineSearchTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Search" });
            var UnityEngineSerializationTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Serialization" });
            var UnityEngineSpritesTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "Sprites" });
            var UnityEngineU2DTable = GetOrCreateNamespaceTable(env, new[] { "UnityEngine", "U2D" });
            //UnityEngineAnalyticsTable = new Lua_UnityEngine_Analytics_AnalyticsEventBase_API();
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Analytics.SendEventOptions);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.AndroidActivityIndicatorStyle);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.AnisotropicFiltering);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ApplicationInstallMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ApplicationMemoryUsage);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ApplicationSandboxType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.AudioType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.BatteryStatus);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Camera+FieldOfViewAxis);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Camera+GateFitMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Camera+MonoOrStereoscopicEye);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Camera+SceneViewFilterMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Camera+StereoscopicEye);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CameraClearFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CameraType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ColorGamut);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ColorPrimaries);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ColorSpace);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CompressionLevel);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CompressionType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ComputeBufferMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ComputeBufferType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CubemapFace);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CursorLockMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CursorMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CustomRenderTextureInitializationSource);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CustomRenderTextureUpdateMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.CustomRenderTextureUpdateZoneSpace);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.DepthTextureMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.DeviceType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Diagnostics.ForcedCrashCategory);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.DrivenTransformProperties);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Events.PersistentListenerMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Events.UnityEventCallState);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FilterMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FindObjectsInactive);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FindObjectsSortMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FogMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FullScreenMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FullScreenMovieControlMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.FullScreenMovieScalingMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.GradientMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.GraphicsBuffer+Target);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.GraphicsBuffer+UsageFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.HDRDisplayBitDepth);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.HDRDisplaySupportFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.HideFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.InspectorSort);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.InspectorSortDirection);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.IntegrityCheckLevel);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.KeyCode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightingSettings+DenoiserType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightingSettings+FilterMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightingSettings+FilterType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightingSettings+Lightmapper);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightingSettings+Sampling);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightmapBakeType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightmapCompression);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightmapsMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightmapsModeLegacy);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+BoundingBoxMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+DataFormat);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+ProbePositionMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+QualityMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+RefreshMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightProbeProxyVolume+ResolutionMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightRenderMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightShadowCasterMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightShadows);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LightType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LineAlignment);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LineTextureMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LODFadeMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LogOption);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.LogType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.MaterialGlobalIlluminationFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.MaterialPropertyType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.MeshTopology);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.MixedLightingMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.MotionVectorGenerationMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.NetworkReachability);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.NPOTSupport);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.OperatingSystemFamily);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.PrimitiveType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Profiling.ProfilerArea);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ReceiveGI);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RectTransform+Axis);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RectTransform+Edge);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ReflectionProbe+ReflectionProbeEvent);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RenderingPath);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RenderTextureCreationFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RenderTextureFormat);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RenderTextureMemoryless);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RenderTextureReadWrite);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RuntimeInitializeLoadType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.RuntimePlatform);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SceneManagement.LoadSceneMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SceneManagement.LocalPhysicsMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SceneManagement.UnloadSceneOptions);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ScreenOrientation);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Scripting.GarbageCollector+Mode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Search.SearchViewFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SendMessageOptions);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ShadowmaskMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ShadowObjectsFilter);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ShadowProjection);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ShadowQuality);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ShadowResolution);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SkinQuality);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SkinWeights);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SnapAxis);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Space);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteAlignment);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteDrawMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteMaskInteraction);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteMeshType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpritePackingMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpritePackingRotation);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteSortPoint);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SpriteTileMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.StackTraceLogType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.StereoTargetEyeMask);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.SystemLanguage);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TerrainQualityOverrides);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TexGenMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.Texture2D+EXRFlags);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TextureFormat);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TextureMipmapLimitBiasMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TextureWrapMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ThreadPriority);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TouchScreenKeyboard+InputFieldAppearance);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TouchScreenKeyboard+Status);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TouchScreenKeyboardType);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TransferFunction);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.TransparencySortMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.UserAuthorization);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.ValidationLevel);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.VRTextureUsage);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.WaitTimeoutMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.WeightedMode);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.WhitePoint);
            //LuaUtil.CreateEnumTable(typeof(UnityEngine.WrapMode);
            //UnityEngineTable = new Lua_UnityEngine_ApplicationMemoryUsageChange_API();
            //UnityEngineTable = new Lua_UnityEngine_Awaitable+AwaitableAsyncMethodBuilder_API();
            //UnityEngineTable = new Lua_UnityEngine_Awaitable+Awaiter_API();
            //UnityEngineTable = new Lua_UnityEngine_BackgroundThreadAwaitable_API();
            //UnityEngineTable = new Lua_UnityEngine_BlendShapeBufferRange_API();
            //UnityEngineTable = new Lua_UnityEngine_BoneWeight_API();
            //UnityEngineTable = new Lua_UnityEngine_BoneWeight1_API();
            //UnityEngineTable = new Lua_UnityEngine_BoundingSphere_API();
            //UnityEngineTable = new Lua_UnityEngine_Bounds_API();
            //UnityEngineTable = new Lua_UnityEngine_BoundsInt_API();
            //UnityEngineTable = new Lua_UnityEngine_BoundsInt+PositionEnumerator_API();
            //UnityEngineTable = new Lua_UnityEngine_BuildCompression_API();
            //UnityEngineTable = new Lua_UnityEngine_Cache_API();
            //UnityEngineTable = new Lua_UnityEngine_CachedAssetBundle_API();
            //UnityEngineTable = new Lua_UnityEngine_Camera+GateFitParameters_API();
            //UnityEngineTable = new Lua_UnityEngine_Color_API();
            //UnityEngineTable = new Lua_UnityEngine_Color32_API();
            //UnityEngineTable = new Lua_UnityEngine_CombineInstance_API();
            //UnityEngineTable = new Lua_UnityEngine_CullingGroupEvent_API();
            //UnityEngineTable = new Lua_UnityEngine_CustomRenderTextureUpdateZone_API();
            //UnityEngineTable = new Lua_UnityEngine_Debug+StartupLog_API();
            //UnityEngineTable = new Lua_UnityEngine_DisplayInfo_API();
            //UnityEngineTable = new Lua_UnityEngine_DrivenRectTransformTracker_API();
            //UnityEngineTable = new Lua_UnityEngine_ExposedPropertyResolver_API();
            //UnityEngineTable = new Lua_UnityEngine_FrameTiming_API();
            //UnityEngineTable = new Lua_UnityEngine_FrustumPlanes_API();
            //UnityEngineTable = new Lua_UnityEngine_GradientAlphaKey_API();
            //UnityEngineTable = new Lua_UnityEngine_GradientColorKey_API();
            //UnityEngineTable = new Lua_UnityEngine_GraphicsBuffer+IndirectDrawArgs_API();
            //UnityEngineTable = new Lua_UnityEngine_GraphicsBuffer+IndirectDrawIndexedArgs_API();
            //UnityEngineTable = new Lua_UnityEngine_GraphicsBufferHandle_API();
            //UnityEngineTable = new Lua_UnityEngine_Hash128_API();
            //UnityEngineTable = new Lua_UnityEngine_InstantiateParameters_API();
            //UnityEngineTable = new Lua_UnityEngine_Keyframe_API();
            //UnityEngineTable = new Lua_UnityEngine_LayerMask_API();
            //UnityEngineTable = new Lua_UnityEngine_LightBakingOutput_API();
            //UnityEngineTable = new Lua_UnityEngine_LightProbesQuery_API();
            //UnityEngineTable = new Lua_UnityEngine_LOD_API();
            //UnityEngineTable = new Lua_UnityEngine_MainThreadAwaitable_API();
            //UnityEngineTable = new Lua_UnityEngine_Mathf_API();
            //UnityEngineTable = new Lua_UnityEngine_Matrix4x4_API();
            //UnityEngineTable = new Lua_UnityEngine_Mesh+MeshData_API();
            //UnityEngineTable = new Lua_UnityEngine_Mesh+MeshDataArray_API();
            //UnityEngineTable = new Lua_UnityEngine_MipmapLimitDescriptor_API();
            //UnityEngineTable = new Lua_UnityEngine_Plane_API();
            //UnityEngineTable = new Lua_UnityEngine_Pose_API();
            //UnityEngineTable = new Lua_UnityEngine_PropertyName_API();
            //UnityEngineTable = new Lua_UnityEngine_Quaternion_API();
            //UnityEngineTable = new Lua_UnityEngine_Random+State_API();
            //UnityEngineTable = new Lua_UnityEngine_RangeInt_API();
            //UnityEngineTable = new Lua_UnityEngine_Ray_API();
            //UnityEngineTable = new Lua_UnityEngine_Ray2D_API();
            //UnityEngineTable = new Lua_UnityEngine_Rect_API();
            //UnityEngineTable = new Lua_UnityEngine_RectInt_API();
            //UnityEngineTable = new Lua_UnityEngine_RectInt+PositionEnumerator_API();
            //UnityEngineTable = new Lua_UnityEngine_RefreshRate_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderBuffer_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderingLayerMask_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderParams_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderTargetSetup_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderTextureDescriptor_API();
            //UnityEngineTable = new Lua_UnityEngine_Resolution_API();
            //UnityEngineSceneManagementTable = new Lua_UnityEngine_SceneManagement_CreateSceneParameters_API();
            //UnityEngineSceneManagementTable = new Lua_UnityEngine_SceneManagement_LoadSceneParameters_API();
            //UnityEngineSceneManagementTable = new Lua_UnityEngine_SceneManagement_Scene_API();
            //UnityEngineTable = new Lua_UnityEngine_SecondarySpriteTexture_API();
            //UnityEngineTable = new Lua_UnityEngine_ShaderVariantCollection+ShaderVariant_API();
            //UnityEngineTable = new Lua_UnityEngine_SortingLayer_API();
            //UnityEngineTable = new Lua_UnityEngine_TagHandle_API();
            //UnityEngineTable = new Lua_UnityEngine_TextureMipmapLimitSettings_API();
            //UnityEngineU2DTable = new Lua_UnityEngine_U2D_SpriteBone_API();
            //UnityEngineTable = new Lua_UnityEngine_Vector2_API();
            //UnityEngineTable = new Lua_UnityEngine_Vector2Int_API();
            //UnityEngineTable = new Lua_UnityEngine_Vector3_API();
            //UnityEngineTable = new Lua_UnityEngine_Vector3Int_API();
            //UnityEngineTable = new Lua_UnityEngine_Vector4_API();
            //UnityEngineTable = new Lua_UnityEngine_AnimationCurve_API();
            //UnityEngineTable = new Lua_UnityEngine_Application_API();
            //UnityEngineTable = new Lua_UnityEngine_YieldInstruction_API();
            //UnityEngineTable = new Lua_UnityEngine_AsyncOperation_API();
            //UnityEngineTable = new Lua_UnityEngine_AsyncInstantiateOperation_API();
            //UnityEngineTable = new Lua_UnityEngine_ResourceRequest_API();
            //UnityEngineTable = new Lua_UnityEngine_Coroutine_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitForEndOfFrame_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitForFixedUpdate_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitForSeconds_API();
            //UnityEngineTable = new Lua_UnityEngine_Awaitable_API();
            //UnityEngineTable = new Lua_UnityEngine_AwaitableCompletionSource_API();
            //UnityEngineTable = new Lua_UnityEngine_Object_API();
            //UnityEngineTable = new Lua_UnityEngine_Component_API();
            //UnityEngineTable = new Lua_UnityEngine_Behaviour_API();
            //UnityEngineTable = new Lua_UnityEngine_Camera_API();
            //UnityEngineTable = new Lua_UnityEngine_FlareLayer_API();
            //UnityEngineTable = new Lua_UnityEngine_LensFlare_API();
            //UnityEngineTable = new Lua_UnityEngine_Light_API();
            //UnityEngineTable = new Lua_UnityEngine_LightProbeGroup_API();
            //UnityEngineTable = new Lua_UnityEngine_LightProbeProxyVolume_API();
            //UnityEngineTable = new Lua_UnityEngine_MonoBehaviour_API();
            //UnityEngineTable = new Lua_UnityEngine_Projector_API();
            //UnityEngineTable = new Lua_UnityEngine_ReflectionProbe_API();
            //UnityEngineTable = new Lua_UnityEngine_Skybox_API();
            //UnityEngineTable = new Lua_UnityEngine_Renderer_API();
            //UnityEngineTable = new Lua_UnityEngine_BillboardRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_LineRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_MeshRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_SkinnedMeshRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_SpriteRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_TrailRenderer_API();
            //UnityEngineTable = new Lua_UnityEngine_LODGroup_API();
            //UnityEngineTable = new Lua_UnityEngine_MeshFilter_API();
            //UnityEngineTable = new Lua_UnityEngine_OcclusionArea_API();
            //UnityEngineTable = new Lua_UnityEngine_OcclusionPortal_API();
            //UnityEngineTable = new Lua_UnityEngine_Transform_API();
            //UnityEngineTable = new Lua_UnityEngine_RectTransform_API();
            //UnityEngineTable = new Lua_UnityEngine_BillboardAsset_API();
            //UnityEngineTable = new Lua_UnityEngine_ComputeShader_API();
            //UnityEngineTable = new Lua_UnityEngine_Texture_API();
            //UnityEngineTable = new Lua_UnityEngine_Cubemap_API();
            //UnityEngineTable = new Lua_UnityEngine_CubemapArray_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderTexture_API();
            //UnityEngineTable = new Lua_UnityEngine_CustomRenderTexture_API();
            //UnityEngineTable = new Lua_UnityEngine_SparseTexture_API();
            //UnityEngineTable = new Lua_UnityEngine_Texture2D_API();
            //UnityEngineTable = new Lua_UnityEngine_Texture2DArray_API();
            //UnityEngineTable = new Lua_UnityEngine_Texture3D_API();
            //UnityEngineTable = new Lua_UnityEngine_Flare_API();
            //UnityEngineTable = new Lua_UnityEngine_GameObject_API();
            //UnityEngineTable = new Lua_UnityEngine_LightingSettings_API();
            //UnityEngineTable = new Lua_UnityEngine_LightmapSettings_API();
            //UnityEngineTable = new Lua_UnityEngine_LightProbes_API();
            //UnityEngineTable = new Lua_UnityEngine_Material_API();
            //UnityEngineTable = new Lua_UnityEngine_Mesh_API();
            //UnityEngineTable = new Lua_UnityEngine_QualitySettings_API();
            //UnityEngineTable = new Lua_UnityEngine_RenderSettings_API();
            //UnityEngineTable = new Lua_UnityEngine_ScriptableObject_API();
            //UnityEngineTable = new Lua_UnityEngine_Shader_API();
            //UnityEngineTable = new Lua_UnityEngine_ShaderVariantCollection_API();
            //UnityEngineTable = new Lua_UnityEngine_Sprite_API();
            //UnityEngineTable = new Lua_UnityEngine_TextAsset_API();
            //UnityEngineU2DTable = new Lua_UnityEngine_U2D_SpriteAtlas_API();
            //UnityEngineTable = new Lua_UnityEngine_Caching_API();
            //UnityEngineTable = new Lua_UnityEngine_ColorGamutUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_ColorUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_ComputeBuffer_API();
            //UnityEngineTable = new Lua_UnityEngine_CrashReport_API();
            //UnityEngineTable = new Lua_UnityEngine_CullingGroup_API();
            //UnityEngineTable = new Lua_UnityEngine_Cursor_API();
            //UnityEngineTable = new Lua_UnityEngine_Debug_API();
            //UnityEngineTable = new Lua_UnityEngine_Display_API();
            //UnityEngineTable = new Lua_UnityEngine_DynamicGI_API();
            //UnityEngineTable = new Lua_UnityEngine_EventProvider_API();
            //UnityEngineEventsTable = new Lua_UnityEngine_Events_UnityEvent_API();
            //UnityEngineTable = new Lua_UnityEngine_ExpressionEvaluator_API();
            //UnityEngineTable = new Lua_UnityEngine_GeometryUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_Gizmos_API();
            //UnityEngineTable = new Lua_UnityEngine_GL_API();
            //UnityEngineTable = new Lua_UnityEngine_Gradient_API();
            //UnityEngineTable = new Lua_UnityEngine_Graphics_API();
            //UnityEngineTable = new Lua_UnityEngine_GraphicsBuffer_API();
            //UnityEngineTable = new Lua_UnityEngine_Handheld_API();
            //UnityEngineTable = new Lua_UnityEngine_HDROutputSettings_API();
            //UnityEngineTable = new Lua_UnityEngine_HmiPlatform_API();
            //UnityEngineTable = new Lua_UnityEngine_iPhoneSettings_API();
            //UnityEngineTable = new Lua_UnityEngine_iPhoneUtils_API();
            //UnityEngineTable = new Lua_UnityEngine_LightmapData_API();
            //UnityEngineTable = new Lua_UnityEngine_LineUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_Logger_API();
            //UnityEngineTable = new Lua_UnityEngine_MaterialPropertyBlock_API();
            //UnityEngineTable = new Lua_UnityEngine_Ping_API();
            //UnityEngineTable = new Lua_UnityEngine_PlayerPrefs_API();
            //UnityEngineProfilingTable = new Lua_UnityEngine_Profiling_Sampler_API();
            //UnityEngineProfilingTable = new Lua_UnityEngine_Profiling_CustomSampler_API();
            //UnityEngineProfilingTable = new Lua_UnityEngine_Profiling_Profiler_API();
            //UnityEngineProfilingTable = new Lua_UnityEngine_Profiling_Recorder_API();
            //UnityEngineTable = new Lua_UnityEngine_RectOffset_API();
            //UnityEngineTable = new Lua_UnityEngine_Resources_API();
            //UnityEngineTable = new Lua_UnityEngine_ResourcesAPI_API();
            //UnityEngineSceneManagementTable = new Lua_UnityEngine_SceneManagement_SceneManager_API();
            //UnityEngineSceneManagementTable = new Lua_UnityEngine_SceneManagement_SceneManagerAPI_API();
            //UnityEngineTable = new Lua_UnityEngine_Screen_API();
            //UnityEngineTable = new Lua_UnityEngine_Security_API();
            //UnityEngineSerializationTable = new Lua_UnityEngine_Serialization_ManagedReferenceUtility_API();
            //UnityEngineSerializationTable = new Lua_UnityEngine_Serialization_UnitySurrogateSelector_API();
            //UnityEngineTable = new Lua_UnityEngine_SleepTimeout_API();
            //UnityEngineSpritesTable = new Lua_UnityEngine_Sprites_DataUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_StaticBatchingUtility_API();
            //UnityEngineTable = new Lua_UnityEngine_SystemInfo_API();
            //UnityEngineTable = new Lua_UnityEngine_Time_API();
            //UnityEngineTable = new Lua_UnityEngine_TouchScreenKeyboard_API();
            //UnityEngineTable = new Lua_UnityEngine_TouchScreenKeyboard+Android_API();
            //UnityEngineTable = new Lua_UnityEngine_TrackedReference_API();
            //UnityEngineU2DTable = new Lua_UnityEngine_U2D_SpriteAtlasManager_API();
            //UnityEngineTable = new Lua_UnityEngine_UnityEventQueueSystem_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitForSecondsRealtime_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitUntil_API();
            //UnityEngineTable = new Lua_UnityEngine_WaitWhile_API();
        }
    }
}
